services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: n9accounts
    ports:
      - "5432:5432"
    volumes:
      - n9accounts_pg:/var/lib/postgresql/data

volumes:
  n9accounts_pg:
